{
 "title": "dc1",
 "time": { "from": "now-1m", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "BGP overall health",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n    count (\n        network_instances_network_instance_protocols_protocol_bgp_neighbors_neighbor_state_session_state == 5\n        and on(source, neighbor_neighbor_address)\n        network_instances_network_instance_protocols_protocol_bgp_neighbors_neighbor_afi_safis_afi_safi_state_enabled{afi_safi_afi_safi_name=\"IPV4_UNICAST\"} ==1\n    )\n    /\n    count (\n        network_instances_network_instance_protocols_protocol_bgp_neighbors_neighbor_afi_safis_afi_safi_state_enabled{afi_safi_afi_safi_name=\"IPV4_UNICAST\"} == 1\n    ) * 100\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "BGP underlay sessions",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count (\n    network_instances_network_instance_protocols_protocol_bgp_neighbors_neighbor_state_session_state == 5\n    and on (source, neighbor_neighbor_address)\n    network_instances_network_instance_protocols_protocol_bgp_neighbors_neighbor_afi_safis_afi_safi_state_enabled{afi_safi_afi_safi_name=\"IPV4_UNICAST\"}\n)",
     "legendFormat": "BGP Established"
    },
    {
     "expr": "count (\n    network_instances_network_instance_protocols_protocol_bgp_neighbors_neighbor_state_session_state != 5\n    and on (source,neighbor_neighbor_address)\n    network_instances_network_instance_protocols_protocol_bgp_neighbors_neighbor_afi_safis_afi_safi_state_enabled{afi_safi_afi_safi_name=\"IPV4_UNICAST\"}\n)",
     "legendFormat": "BGP Not Established"
    }
   ]
  },
  {
   "title": "BGP overlay sessions",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count (\n    network_instances_network_instance_protocols_protocol_bgp_neighbors_neighbor_state_session_state == 5\n    and on (source, neighbor_neighbor_address)\n    network_instances_network_instance_protocols_protocol_bgp_neighbors_neighbor_afi_safis_afi_safi_state_enabled{afi_safi_afi_safi_name=\"L2VPN_EVPN\"}\n)",
     "legendFormat": "BGP Established"
    },
    {
     "expr": "count (\n    network_instances_network_instance_protocols_protocol_bgp_neighbors_neighbor_state_session_state != 5\n    and on (source, neighbor_neighbor_address)\n    network_instances_network_instance_protocols_protocol_bgp_neighbors_neighbor_afi_safis_afi_safi_state_enabled{afi_safi_afi_safi_name=\"L2VPN_EVPN\"}\n)",
     "legendFormat": "BGP Not Established"
    }
   ]
  },
  {
   "title": "Interface rx rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "rate (\n    interfaces_interface_state_counters_in_octets{interface_name=~\"^ge-.*\"}[15s]\n) * 8",
     "legendFormat": "{{source}} - {{interface_name}}"
    }
   ]
  },
  {
   "title": "Interface tx rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "rate (\n    interfaces_interface_state_counters_out_octets{interface_name=~\"^ge-.*\"}[15s]\n) * 8",
     "legendFormat": "{{source}} - {{interface_name}}"
    }
   ]
  },
  {
   "title": "BGP logs",
   "type": "logs",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 35 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{app=\"rpd\"} |= ``"
    }
   ]
  }
 ]
}