---
role: 'spine'
interfaces:
        lo0:
                address: '192.168.100.2/32'
        xe-0/0/0:
                address: '10.10.0.3/31'
        xe-0/0/1:
                address: '10.10.0.7/31'
        xe-0/0/2:
                address: '10.10.0.11/31'
        xe-0/0/3:
                address: '10.10.0.15/31'
        xe-0/0/4:
                address: '10.10.0.19/31'
bgp:
        as_number: 65500
        router_id: '192.168.100.2'
        neighbors:
                10.10.0.2:
                        remote_as: 65421
                        loopback: '192.168.10.1'
                10.10.0.6:
                        remote_as: 65422
                        loopback: '192.168.10.2'
                10.10.0.10:
                        remote_as: 65423
                        loopback: '192.168.10.3'
                10.10.0.14:
                        remote_as: 65424
                        loopback: '192.168.10.4'
                10.10.0.18:
                        remote_as: 65425
                        loopback: '192.168.10.5'
switch_options:
        rd: '192.168.100.2:65500'
        vrf_target: '65500:1'
        vtep_source: 'lo0.0'
