---

- name: Automated deployment of a 3-stage two leaf, two spine Juniper CRB design
  hosts: all
  tasks:
    - name: configuring p2p fabric interfaces
      cli_config:
        config: "{{ lookup('template', 'templates/p2p_fabric_interface_creation.j2') }}"
    - name: configuring policies on devices
      cli_config:
        config: "{{ lookup('template', 'templates/policy.j2') }}"
    - name: configuring BGP on devices
      cli_config:
        config: "{{ lookup('template', 'templates/bgp.j2') }}"
    - name: configuring VLANs and EVPN services on leafs
      when: inventory_hostname in groups["leafs"]
      cli_config:
        config: "{{ lookup('template', 'templates/evpn.j2') }}"
    - name: mapping VLANs to host facing interfaces
      when: inventory_hostname in groups["leafs"]
      cli_config:
        config: "{{ lookup('template', 'templates/vlan_mapping.j2') }}"
    - name: configuring IRB interfaces on CRB devices
      when: inventory_hostname in groups["crb"]
      cli_config:
        config: "{{ lookup('template', 'templates/irb_interfaces.j2') }}"
    - name: configuring VLANs and mapping them to IRB interfaces on CRB devices
      when: inventory_hostname in groups["crb"]
      cli_config:
        config: "{{ lookup('template', 'templates/vlans_crb.j2') }}"
    - name: configuring EVPN parameters and mapping VLANs to VNIs on CRB devices
      when: inventory_hostname in groups["crb"]
      cli_config:
        config: "{{ lookup('template', 'templates/evpn_crb.j2') }}"
    - name: configuring policy communities for CRB
      when: inventory_hostname in groups["leafs"]
      cli_config:
        config: "{{ lookup('template', 'templates/communities_crb.j2') }}" 
    - name: configuring CRB policies on leafs
      when: inventory_hostname in groups["leafs"]
      cli_config:
        config: "{{ lookup('template', 'templates/policy_crb.j2') }}"
