---
location: "dc2"
role: 'spine'
crb_enabled: 'true'
interfaces:
        lo0:
                address: '192.168.100.3/32'
        xe-0/0/0:
                address: '10.10.0.30/31'
        xe-0/0/4:
                address: '10.10.0.20/31'
        xe-0/0/5:
                address: '10.10.0.22/31'
bgp:
        as_number: 65501
        router_id: '192.168.100.3'
        neighbors:
                10.10.0.21:
                        remote_as: 65500
                        loopback: '192.168.100.1'
                10.10.0.23:
                        remote_as: 65500
                        loopback: '192.168.100.2'
                10.10.0.31:
                        remote_as: 65423
                        loopback: '192.168.10.3'
switch_options:
        rd: '192.168.100.3:65501'
        vrf_target: '65501:1'
        vtep_source: 'lo0.0'
vlans:
        100:
                vni: 10100
                name: 'VLAN100'
                rt: '100:100'
                l3_interface: 'irb.100'
        200:
                vni: 10200
                name: 'VLAN200'
                rt: '200:200'
                l3_interface: 'irb.200'
irb:
        100:
                v4_address: '10.100.100.252/24'
                v4_vga: '10.100.100.254'
        200:
                v4_address: '10.100.200.252/24'
                v4_vga: '10.100.200.254'
