---
role: 'leaf'
ae_number: 5
interfaces:
        lo0:
                address: '192.168.10.2/32'
        xe-0/0/0:
                address: '10.10.0.4/31'
        xe-0/0/1:
                address: '10.10.0.6/31'
bgp:
        as_number: 65422
        router_id: '192.168.10.2'
        neighbors:
                10.10.0.5:
                        remote_as: 65500
                        loopback: '192.168.100.1'
                10.10.0.7:
                        remote_as: 65500
                        loopback: '192.168.100.2'
esi:
        ae0:
                interfaces:
                        - 'xe-0/0/2'
                system_id: '00:00:00:00:00:11'
                esi_id: 'auto'
communities:
        leaf1-type1:
                - 'target:65421:1'
policies:
        policy_statements:
                Leaf2_Import:
                        terms:
                                leaf1_type1:
                                        community: 'leaf1-type1'
switch_options:
        rd: '192.168.10.2:65422'
        vrf_target: '65422:1'
        vtep_source: 'lo0.0'
vlans:
        100:
                vni: 10100
                name: 'v10'
                rt: '100:100'
                interfaces:
                        - 'ae0' 
