---
role: 'leaf'
ae_number: 5
interfaces:
        lo0:
                address: '192.168.10.1/32'
        xe-0/0/0:
                address: '10.10.0.0/31'
        xe-0/0/1:
                address: '10.10.0.2/31'
bgp:
        as_number: 65421
        router_id: '192.168.10.1'
        neighbors:
                10.10.0.1:
                        remote_as: 65500
                        loopback: '192.168.100.1'
                10.10.0.3:
                        remote_as: 65500
                        loopback: '192.168.100.2'
esi:
        ae0:
                interfaces:
                        - 'xe-0/0/2'
                system_id: '00:00:00:00:00:11'
                esi_id: 'auto'
communities:
        leaf2-type1:
                - 'target:65422:1'
policies:
        policy_statements:
                Leaf1_Import:
                        terms:
                                leaf2_type1:
                                        community: 'leaf2-type1'
switch_options:
        rd: '192.168.10.1:65421'
        vrf_target: '65421:1'
        vtep_source: 'lo0.0'
vlans:
        100:
                vni: 10100
                name: 'v10'
                rt: '100:100'
                interfaces:
                        - 'ae0' 
